#!/bin/sh

useradd student -p $(echo password | openssl passwd -stdin -1) -G wheel
usermod root -p $(echo redhat | openssl passwd -stdin -1)

sed -i s'/^#\(PermitRootLogin yes\)$/\1/' /etc/ssh/sshd_config

systemctl enable firewalld.service
systemctl start firewalld.service

yum -y update
yum -y install -y centos-release-openstack-mitaka
yum -y install openstack-packstack

# packstack
# packstack [options]
# packstack --gen-answer-file=<file> [options] / packstack --answer-file=<file>

packstack --install-hosts=192.168.121.150 --novanetwork-pubif=eth1 --novacompute-privif=lo --novanetwork-privif=lo --os-swift-install=y --nagios-install=y --default-password=password